name: Cypress tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Set up Docker Compose
        run: docker-compose up -d
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PORT: 3000

      - name: Wait for Server and Database
        run: sleep 15

      - name: Check containers
        run: docker ps

      - name: View database container logs
        run: |
          echo "Current Docker containers:"
          docker ps

          echo "Fetching database container ID..."
          DATABASE_CONTAINER_ID=$(docker ps -qf "name=_database_1" | awk 'NR==1{print $1}')

          if [ -z "$DATABASE_CONTAINER_ID" ]; then
            echo "Database container not found"
            exit 1
          fi

          echo "Found database container ID: $DATABASE_CONTAINER_ID"
          docker logs $DATABASE_CONTAINER_ID

      - name: View backend container logs
        run: |
          echo "Current Docker containers:"
          docker ps

          echo "Fetching backend container ID..."
          BACKEND_CONTAINER_ID=$(docker ps -qf "name=_backend_1" | awk 'NR==1{print $1}')

          if [ -z "$BACKEND_CONTAINER_ID" ]; then
            echo "Backend container not found"
            exit 1
          fi

          echo "Found backend container ID: $BACKEND_CONTAINER_ID"
          docker logs $BACKEND_CONTAINER_ID

      - name: View frontend container logs
        run: |
          echo "Current Docker containers:"
          docker ps

          echo "Fetching frontend container ID..."
          FRONTEND_CONTAINER_ID=$(docker ps -qf "name=_frontend_1" | awk 'NR==1{print $1}')

          if [ -z "$FRONTEND_CONTAINER_ID" ]; then
            echo "Frontend container not found"
            exit 1
          fi

          echo "Found frontend container ID: $FRONTEND_CONTAINER_ID"
          docker logs $FRONTEND_CONTAINER_ID

      - name: Test backend endpoint city
        run: |
          docker compose exec -it backend /bin/bash
          curl -v http://localhost:3000/city

      - name: Run Cypress tests
        run: |
          docker compose exec -it frontend npm run test
